spring.application.name=backend
spring.data.mongodb.uri=mongodb://admin:password@hughdell.local:27017/admin
fdc-api-key=fqb4Fojb2agvj6XQOiYX86LtYJPvqXCYlAv4oTsa
security.key=hnvsjahblijfqrnokmfn4849jwoijf84nfnejek4eoi4ioirenknvorejno